version: "3.7"

services:

  whoareyou:
    hostname: "{{.Service.Name}}-{{.Task.Slot}}-{{.Node.Hostname}}"
    image: "containous/whoami"
    networks:
      - traefik-public
    volumes:
      - datavolume:/etc
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoareyou.rule=Host(`whoareyou.$DOMAIN`)"
        - "traefik.http.routers.whoareyou.entrypoints=websecure"
        - "traefik.http.routers.whoareyou.tls=true"
        - "traefik.http.routers.whoareyou.tls.certresolver=letsencryptresolver"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.services.whoareyou.loadbalancer.server.port=80"
        - "traefik.http.routers.whoareyou.middlewares=admin"
volumes:
  datavolume:
networks:
  traefik-public:
    external: true
