version: "3.8"

services:

  whoareyou:
    hostname: "{{.Service.Name}}-{{.Task.Slot}}-{{.Node.Hostname}}"
    image: traefik/whoami:latest
    networks:
      - host
    ports:
      - 8888:80
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoareyou.rule=Host(`whoareyou.$DOMAIN`)"
        - "traefik.http.routers.whoareyou.entrypoints=websecure"
        - "traefik.http.routers.whoareyou.tls=true"
        - "traefik.http.routers.whoareyou.tls.certresolver=letsencryptresolver"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.services.whoareyou.loadbalancer.server.port=80"
        - "traefik.http.routers.whoareyou.middlewares=admin"

networks:
  host:
    external: true
