version: "3.8"

services:

  whoareyou:
    hostname: "{{.Service.Name}}-{{.Node.Hostname}}"
    image: traefik/whoami:latest
    networks:
      - traefik-public
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoareyou.rule=Host(`whoareyou.$DOMAIN`)"
        - "traefik.http.routers.whoareyou.entrypoints=websecure"
        - "traefik.http.routers.whoareyou.tls=true"
        - "traefik.http.routers.whoareyou.tls.certresolver=letsencryptresolver"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.services.whoareyou.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
